name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up env user
      run: echo USER=${{ secrets.USER }} >> .env.prod
    - name: Set up env password    
      run:  echo PASSWORD=${{ secrets.PASSWORD }}" >> .env.prod
    - name: Set up env url
      run:  echo URL=${{ secrets.URL }} >> .env.prod
    - name: Set up env firebase
      run:  echo "FIREBASE_CREDENTIALS='${{ secrets.FIREBASE_CREDENTIALS }}'" >> .env.prod
    - name: Set up env imgbb
      run:  echo IMGBB_KEY=${{ secrets.IMGBB_KEY }} >> .env.prod

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"